[JBPM-9308] EventEmitter is not working in spring boot
kiegroup/droolsjbpm-integration pull request #2208
Opened 2020-08-26 09:09 UTC by elguardian

Jira:
https://issues.redhat.com/browse/JBPM-9308

2020-08-26 09:09 UTC, elguardian commented
depends on https://github.com/kiegroup/jbpm/pull/1738

2020-08-26 13:50 UTC, afalhambra requested changes
There is file change which is not needed in this PR. 

I would add a simple test for the Emitter here.

Other than that, everything looks fine.

2020-08-27 09:54 UTC, elguardian commented
Jenkins retest this please.

2020-08-28 09:42 UTC, elguardian commented on kie-spring-boot/kie-spring-boot-autoconfiguration/jbpm-spring-boot-autoconfiguration/src/main/java/org/jbpm/springboot/services/SpringRegisterableItemsFactory.java
> +import org.jbpm.persistence.api.integration.EventEmitter;
done

2020-08-28 10:22 UTC, afalhambra approved these changes
Nice work @elguardian, just wait for CI to clean.

2020-08-28 14:11 UTC, merged