[JBPM-9317] Add test for springboot userTaskService.saveContent
kiegroup/droolsjbpm-integration pull request #2219
Opened 2020-09-02 10:29 UTC by gmunozfe

**JIRA**:  [JBPM-9317](https://issues.redhat.com/browse/JBPM-9317)

Added springboot test for checking saveContent accesibility during deadline notification

2020-09-03 00:18 UTC, gmunozfe commented
jenkins retest this

2020-09-04 07:43 UTC, elguardian commented on kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/DeadlinesNotificationTest.java
> +        assertNotNull(processInstanceId);
Cannot never be null

2020-09-04 07:43 UTC, elguardian requested changes
some change otherwise LGTM

2020-09-04 12:54 UTC, gmunozfe commented on kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/DeadlinesNotificationTest.java
> +        assertNotNull(processInstanceId);
OK, fixed, thanks for the review!

2020-09-07 07:19 UTC, elguardian approved these changes

2020-09-07 07:19 UTC, merged

2020-09-07 07:20 UTC, elguardian commented
thx @gmunozfe