[JBPM-9178] Immutable SpringBoot Deployment / Adding controller conne…
kiegroup/droolsjbpm-integration pull request #2220
Opened 2020-09-02 10:29 UTC by elguardian

under test.

2020-09-02 14:20 UTC, elguardian commented
depends on https://github.com/kiegroup/droolsjbpm-integration/pull/2220

2020-09-03 06:36 UTC, elguardian commented
Jenkins retest this please.

2020-09-04 14:25 UTC, afalhambra requested changes
Some minor changes required. 
I would try to cover these scenarios adding some test cases, as test coverage is quite low here.

2020-09-07 08:01 UTC, elguardian commented on kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/src/main/java/org/kie/server/springboot/EmbeddedKieJar.java
> +package org.kie.server.springboot;
done

2020-09-07 08:03 UTC, elguardian commented on kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/src/main/java/org/kie/server/springboot/autoconfiguration/KieServerAutoConfiguration.java
> +    @ConditionalOnProperty(name = "kieserver.autosScanDeployements", havingValue = "true")
chage to autoScanDeployments

2020-09-07 08:04 UTC, elguardian commented on kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/src/main/java/org/kie/server/springboot/autoconfiguration/KieServerAutoConfiguration.java
> +                    }
done

2020-09-07 08:06 UTC, elguardian commented on kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/InmutableContainerStartupStrategy.java
> +        this.kieContainers = kieContainer.stream().collect(toSet());
done

2020-09-07 08:06 UTC, elguardian commented on kie-server-parent/kie-server-services/kie-server-services-common/src/main/resources/META-INF/services/org.kie.server.services.api.StartupStrategy
> -org.kie.server.services.impl.InmutableContainerStartupStrategy
It can cause some problem in other deploye due to startup logic strategy.

2020-09-07 08:07 UTC, elguardian commented on kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/storage/memory/InMemoryKieServerStateRepository.java
> -            newState.setControllers(new HashSet<>());
It modifies env variables so you cannot get the url controller from application properties.

2020-09-07 08:08 UTC, elguardian commented on kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/src/main/java/org/kie/server/springboot/autoconfiguration/KieServerAutoConfiguration.java
> +    @ConditionalOnProperty(name = "kieserver.autosScanDeployements", havingValue="false", matchIfMissing = true)
I think it is more convenient but it seems consultants want to set the container name. that is not possible automatically.

2020-09-07 08:08 UTC, elguardian commented on kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/src/main/java/org/kie/server/springboot/autoconfiguration/KieServerAutoConfiguration.java
> +    @ConditionalOnProperty(name = "kieserver.autosScanDeployements", havingValue = "true")
same as above

2020-09-07 09:37 UTC, afalhambra requested changes
Just some previous comment not resolved yet

2020-09-07 09:37 UTC, afalhambra commented on kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/InmutableContainerStartupStrategy.java
>  public class InmutableContainerStartupStrategy implements StartupStrategy {
this not resolved yet

2020-09-07 09:37 UTC, afalhambra commented on kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/src/main/java/org/kie/server/springboot/autoconfiguration/KieServerAutoConfiguration.java
> +                }
this is not changed yet

2020-09-07 09:37 UTC, afalhambra commented on kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/src/main/java/org/kie/server/springboot/autoconfiguration/KieServerAutoConfiguration.java
> +                }
not closed yet

2020-09-07 09:37 UTC, afalhambra commented on kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/src/main/java/org/kie/server/springboot/autoconfiguration/KieServerAutoConfiguration.java
> +        return isDeployable ? Optional.ofNullable(resource) : Optional.empty();
what about this?

2020-09-07 09:45 UTC, elguardian commented on kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/src/main/java/org/kie/server/springboot/autoconfiguration/KieServerAutoConfiguration.java
> +        return isDeployable ? Optional.ofNullable(resource) : Optional.empty();
isDeployable does not guarantaed to have the pom so you don't know about the resource being found or not.

2020-09-07 10:05 UTC, afalhambra approved these changes
Amazing job! very easy and intuitive to use. well done

2020-09-08 06:31 UTC, merged