[JBPM-9323] Some form options can't be rendered in API response / MultipleSelector
kiegroup/droolsjbpm-integration pull request #2246
Opened 2020-09-22 09:39 UTC by elguardian

JIRA: https://issues.redhat.com/browse/JBPM-9323

2020-09-24 06:53 UTC, afalhambra requested changes
Overall looks good with the exception of the `MultipleInput` which does not work in Wildfly (reason being is explained in the review). Listing below the issues found.

For `MultipleSelector`:

- There is no "Search filter" as specified in the task form on BC.
- There is no "Clear selection action" as specified in the task form on BC.
- "Elements visible on the dropdown" has no effect on the task form.
- "Elements visible on dropdown title" has no effect on the task form.
- "Required" has no effect on the task form.
- "Help message" doesn't come up.

For "MultipleInput":
- Values entered in the field are not stored, they're gone once you get back to the task even after saving or completing the task.
- "Help message" doesn't come up.
- "Page size" has no effect.
- "Required" has no effect on the task form.

2020-09-24 08:06 UTC, elguardian commented
Hi @afalhambra  it is not required for jbpm form ui kie server to work exactly as BC

2020-09-25 06:14 UTC, afalhambra commented
> Hi @afalhambra it is not required for jbpm form ui kie server to work exactly as BC

Ok, fine with me. However there are two main outstanding issues as mention in the review:

- `MultipleInput` doesn't get displayed when using Wildfly
- `MultipleInput` inputs are not being saved/stored once the task is either saved or complete.

Would you please have a look?

2020-09-28 07:23 UTC, elguardian commented on kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/form/render/AbstractFormRenderer.java
>  import static java.util.Collections.singletonList;
done

2020-09-28 07:23 UTC, elguardian commented on kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/form/render/AbstractFormRenderer.java
> +import java.util.StringJoiner;
done

2020-09-28 07:23 UTC, elguardian commented on kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/form/render/AbstractFormRenderer.java
> +                                    item.setOptions(field.getListOfValues().stream().map(e -> new ItemOption(e)).collect(toList()));
done

2020-09-28 07:23 UTC, elguardian commented on kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/form/render/AbstractFormRenderer.java
> +        } else if (type.contains("Document") || type.contains("documentCollection") || type.contains("multipleSelector") || type.contains("multipleInput") || type.contains("Date")) {
done

2020-09-28 07:24 UTC, elguardian commented on kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/resources/form-templates-providers/patternfly/input-form-group-template.html
> +</div>
done

2020-09-28 08:40 UTC, afalhambra approved these changes
Thanks @elguardian - nice job.

2020-09-28 10:46 UTC, merged