[JBPM-9423] Duplicate container-info entries in kie-server-router.jso…
kiegroup/droolsjbpm-integration pull request #2282
Opened 2020-10-13 10:45 UTC by elguardian

Jira: https://issues.redhat.com/browse/JBPM-9423

2020-10-13 14:48 UTC, gmunozfe requested changes
Test failures related with the PR:
https://github.com/kiegroup/droolsjbpm-integration/blob/2d3b1c96e52117b7f7179b30c4e38270d7a6a900/kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/ConfigurationTest.java#L152-L153
A different alias is needed to fix that test

2020-10-13 14:48 UTC, gmunozfe commented on kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/ConfigurationTest.java
> +        assertEquals(3, configuration.getHostsPerServer().get("default-kieServer").size());
This line is duplicated

2020-10-19 07:08 UTC, elguardian commented on kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/ConfigurationTest.java
> +        assertEquals(3, configuration.getHostsPerServer().get("default-kieServer").size());
done

2020-10-21 10:37 UTC, gmunozfe approved these changes
Just a single comment, if you want to handle it by refactoring and extracting the configuration "add..." invocations.
Otherwise, looks good to me, fantastic work @elguardian !

2020-10-28 07:53 UTC, merged