JBPM-9410 - No Model definition in KIE Server Swagger API - revapi fix
kiegroup/droolsjbpm-integration pull request #2294
Opened 2020-10-22 10:34 UTC by MarianMacik

**JIRA**: [JBPM-9410](https://issues.redhat.com/browse/JBPM-9410)

Follow-up of #2263 

We don't need to ignore every potentially breaking change. Revapi ignores work like filters and the less specific the filter is, the more it will ignore. So there is no need to ignore them one by one :) If we left the current configuration (only breaking changes are failing the build), we would miss any potential changes in future regarding endpoints, i.e. JAX-RS annotations configuration.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

2020-10-22 11:16 UTC, afalhambra requested changes
This one needs to be fixed as well as part of https://github.com/kiegroup/droolsjbpm-integration/pull/2263 PR:

https://github.com/kiegroup/droolsjbpm-integration/blob/master/kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/pom.xml#L178

2020-10-22 13:36 UTC, fjtirado approved these changes
Thanks a lot Marian, I did not know we can ignore a group of annotations though ignore revapi.

2020-10-22 14:03 UTC, MarianMacik commented
@afalhambra Thanks for pointing it out, now I fixed also the second file.
@fjtirado No problem, now you know :) I didin't know it either some time ago.

2020-10-23 08:46 UTC, afalhambra approved these changes
Nice job. Thanks @MarianMacik

2020-10-26 08:27 UTC, merged