JBPM-9979: Mark async active nodes and change default active node border
kiegroup/droolsjbpm-integration pull request #2732
Opened 2022-03-10 16:39 UTC by nmirasch

Jira: https://issues.redhat.com/browse/JBPM-9979  

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

2022-03-10 16:48 UTC, nmirasch commented
@bxf12315 I've created this PR based in your commit related with the errorBorderColor in order to:
- Keep backward compatibility just adding new calls to allow to use the new color option.
- Replace the references to errorBorderColor by asyncActiveborderColor.
- I've replaced the test by something we can found in real execution to try the fullLogs logic with a real case

Could you take a look on this one to see if there is something missing here?

2022-03-11 03:34 UTC, bxf12315 commented
> @bxf12315 I've created this PR based in your commit related with the errorBorderColor in order to:
> 
> * Keep backward compatibility just adding new calls to allow to use the new color option.
I do not know why we need to create a new call? the reset call's any params could be null.  the rest API just using one places.  

> * Replace the references to errorBorderColor by asyncActiveborderColor.
Maybe failedAsyncNodeBoraderColor is better.
> * I've replaced the test by something we can found in real execution to try the fullLogs logic with a real case
> 
> Could you take a look on this one to see if there is something missing here?

2022-03-11 07:09 UTC, nmirasch commented
@bxf12315 Thanks,
* the thing is to avoid to change the current existing calls introducing that needed null. Just adding a new call if it needs to used the new border color conf, in order to avoid break in case someone is using the old one..
* failedAsyncNodeBorderColor implies it's failing but it's not completely true. They are async nodes that not have been completed yet.. At this point we can't differentiate between in 'error' or 'queued' ones.. that's the reason to use 'active' instead

2022-03-11 07:12 UTC, nmirasch commented
Jenkins retest this

2022-03-11 07:42 UTC, bxf12315 commented
> * oid to change the current existing calls introducing t



> @bxf12315 Thanks,
> 
> * the thing is to avoid to change the current existing calls introducing that needed null. Just adding a new call if it needs to used the new border color conf, in order to avoid break in case someone is using the old one..
> * failedAsyncNodeBorderColor implies it's failing but it's not completely true. They are async nodes that not have been completed yet.. At this point we can't differentiate between in 'error' or 'queued' ones.. that's the reason to use 'active' instead

The two rest API has the same URL path, just has different query param and it's a GET. Maybe you new param is not work.
and I think it do not break other exits call, if the param is null, the the call also work.
Do you try the code, the async nodes is work?

2022-03-11 08:40 UTC, nmirasch commented
@bxf12315  yes, I agree we can keep just one rest endpoint.(I'm going to add that change now)  The issue was regarding the api changes method java.lang.String org.kie.server.client.UIServicesClient::getProcessInstanceImageCustomColor with different number or parameters could make mandatory to introduce changes in older calls, to use kie-server with this change.

2022-03-11 09:44 UTC, bxf12315 commented
@nmirasch the code also not work. QueryParam's ASYNC_ACTIVE_BORDER_COLOR, will not work. you need to use "SVG_NODE_ASYNC_ACTIVE_BORDER_COLOR"

2022-03-14 07:40 UTC, cristianonicolai approved these changes

2022-03-15 09:51 UTC, barboras7 requested changes

2022-03-15 09:51 UTC, barboras7 commented on kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/UIServicesClient.java
> +     * @param activeAsyncNodeBorderColor process instance image error node border color
```suggestion
     * @param activeAsyncNodeBorderColor process instance image active async node border color
```

2022-03-16 01:18 UTC, cristianonicolai commented
jenkins please retest this

2022-03-16 03:56 UTC, bxf12315 commented
> jenkins please retest this

Please don't merge this, it's a duplicate PR.

2022-03-16 10:02 UTC, barboras7 approved these changes

2022-03-17 08:45 UTC, closed without merging