[JBPM-10045] Incorrect response for REST service when "org.kie.server bypass.auth.user" used with Spring Boot Runtime
kiegroup/droolsjbpm-integration pull request #2750
Opened 2022-03-22 10:32 UTC by elguardian

Jira: https://issues.redhat.com/browse/JBPM-10045

depends on https://github.com/kiegroup/droolsjbpm-knowledge/pull/596

2022-04-08 12:49 UTC, gmunozfe requested changes
Some changes are required in the spring-boot sample. Perhaps a test with enabled bypass for spring-boot would be useful.

2022-04-11 16:08 UTC, yesamer commented
jenkins retest this please

2022-04-13 07:30 UTC, afalhambra approved these changes
Tested from my side with the bypass test cases and works fine.
Nice job @elguardian

2022-04-13 07:41 UTC, elguardian commented on kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/main/java/org/kie/server/springboot/samples/KeycloakIdentityProvider.java
> +                        return userResource.groups().stream().map(e -> e.getName()).collect(Collectors.toList());
done

2022-04-18 15:26 UTC, gmunozfe commented on kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/main/java/org/kie/server/springboot/samples/KeycloakIdentityProvider.java
> +                        usersResource.get(user.getId()).roles().realmLevel().listAll().stream().map(RoleRepresentation::getName).collect(Collectors.toList());
missing return statement

2022-04-18 15:27 UTC, gmunozfe requested changes
missing return statement at getRolesFor

2022-04-21 16:21 UTC, gmunozfe commented on kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/test/resources/application-test.properties
> +keycloak-identity.admin.pwd=admin
@elguardian Sorry, wrong suggestion, these are springboot properties from context, not system properties. 
A test is failing because of this change

2022-04-22 06:48 UTC, elguardian commented
Jenkins retest this please

2022-05-04 08:57 UTC, elguardian commented
Jenkins retest this please

2022-05-09 09:04 UTC, elguardian commented
Jenkins retest this please

2022-05-11 07:59 UTC, merged