[RHPAM-4898] Fix concurrency issue in KafkaServerRegistration
kiegroup/droolsjbpm-integration pull request #3034
Opened 2024-02-29 21:07 UTC by martinweiler

Related JIRA: https://issues.redhat.com/browse/RHPAM-4898

2024-03-01 07:13 UTC, elguardian commented
Jenkins retest this please

2024-03-01 07:36 UTC, elguardian requested changes

2024-03-01 07:36 UTC, elguardian commented on kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerRegistration.java
> +    void close() {
do not remove

2024-03-01 07:36 UTC, elguardian commented on kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerRegistration.java
> +    boolean isEmpty() {
do not remove

2024-03-01 07:36 UTC, elguardian commented on kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerRegistration.java
> +    Set<String> addRegistration(DeploymentEvent event) {
do not remove

2024-03-01 07:36 UTC, elguardian commented on kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerRegistration.java
> +    Set<String> removeRegistration(DeploymentEvent event, Consumer<String> topicProcessed) {
do not remove

2024-03-01 15:39 UTC, martinweiler commented
Thanks @elguardian - please review now.

2024-03-01 17:31 UTC, elguardian approved these changes

2024-03-04 09:33 UTC, mareknovotny commented
> Jenkins retest this please

Jenkins is not triggered on all branches, just selected maintained ones. so this is useless, you can see only GHA CI

2024-03-04 14:54 UTC, elguardian commented
@martinweiler we need this against main

2024-03-06 07:57 UTC, merged